# Generated by Django 2.1.8 on 2019-05-24 20:16

import core.users.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20190524_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='default-profile.jpg', upload_to=core.users.models.save_image_path),
        ),
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.DateField(blank=True, default=datetime.date(1987, 2, 15), null=True),
        ),
    ]
