# Generated by Django 2.1.8 on 2019-05-24 20:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20190524_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.DateField(blank=True, default=datetime.date(1970, 1, 1), null=True),
        ),
    ]
